### ISSUE TITLE
Use yml file instead of json for configuration

### ISSUE THREAD

**Issue by subhojit777** [srijanaravali/drupal-starter-kit#11]
One thing I found while I was reading `config.json` - there are no comments, and I have to read the code to  understand what is the purpose of every line. And you just cannot write comments in JSON (see http://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

Using YAML we will have the benefit of human friendly code + comments for easy understanding.

**Comment by AshishThakur** [comment]
Yes please raise a PR :)
