### ISSUE TITLE
Gulp Build not detecting PHP Validation Errors

### ISSUE THREAD

**Issue by rishantagarwal** [srijanaravali/drupal-starter-kit#24]
1. Below line when using PHP Code Sniffer to validate PHP code, does not terminates the build on any error. Reason being the below code just runs it as a shell command and is unable to detect errors as an event. It just gets parsed as text.
`var report = execSync('./vendor/bin/phpcs --standard="./.phpcsrc.xml" ' + file.path);`

2. I am using plugin `gulp-phpcs` to change that and is then able to detect errors. It works fine now. 

`var phpcs = require('gulp-phpcs');`

`return gulp.src(sourcePatterns)`
    `.pipe(phpcs({`
   `   bin: './vendor/bin/phpcs',`
     ` standard :  './.phpcsrc.xml',`
     ` warningSeverity: 0`
    `}))`
    `.pipe(phpcs.reporter('log'))`
    `.pipe(phpcs.reporter('fail'));`

`});`

**Comment by AshishThakur** [comment]
Thanks @rishantagarwal, works great 👍

**Comment by AshishThakur** [comment]
I will commit your changes and close this.
